#pragma once

#define NAMESPACE_GL namespace gl {
#define NAMESPACE_GL_END }

#define NAMESPACE_RENDER NAMESPACE_GL namespace render {
#define NAMESPACE_RENDER_END NAMESPACE_GL_END }

#define NAMESPACE_EVENT NAMESPACE_GL namespace event {
#define NAMESPACE_EVENT_END NAMESPACE_GL_END }

#define NAMESPACE_CONTROLLER NAMESPACE_GL namespace ctrl {
#define NAMESPACE_CONTROLLER_END NAMESPACE_GL_END }

#define NAMESPACE_ENTITY NAMESPACE_GL namespace ent {
#define NAMESPACE_ENTITY_END NAMESPACE_GL_END }
